### ISSUE TITLE
Create a PIP official package of this node

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/ObjectDetector#32]
Maybe naming it jderobot-objectdetector to avoid collision with other packages

**Comment by ayushmankumar7** [comment]
I am Working on this.

**Comment by ayushmankumar7** [comment]
I was tried creating a pip package. Please check my PR.

**Comment by naxvm** [comment]
Thank you for your contribution Ayushman! We have merged the changes into the master branch. However we are currently migrating this node to work with Python 3 and ROS Melodic (#47), so maybe we have to re-build the package again when this is complete. As I checked, the pip package you configured is suitable for Python 2, but would be great if you want to re-build the package with Python3!

**Comment by ayushmankumar7** [comment]
Sure ! I am rebuilding it for Python3 then.
