### ISSUE TITLE
Porting the detector to ROS Melodic + Python 3

### ISSUE THREAD

**Issue by naxvm** [JdeRobot/ObjectDetector#47]

**Comment by naxvm** [comment]
As we are not ussing the `comm` middleware anymore, the ICE support has to be implemented from scratch.

**Comment by jmplaza** [comment]
Let's use ROS for communicating with image driver. No?

**Comment by naxvm** [comment]
Yes, I'm working on porting the [ROSCam](https://github.com/RoboticsLabURJC/2017-tfg-nacho_condes/blob/master/Camera/ROSCam.py) from the TFM (direct interface using ```rospy```).

**Comment by naxvm** [comment]
Fixed on #56
