### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by ayushmankumar7** [JdeRobot/ObjectDetector#49]
The Tensorflow code used here is from the Tensorflow 1.x  but in the requirements.txt it's just mentioned tensorflow which automatically installs the lastest verison of Tensroflow (TF2.1.0).
Now, there can be two things done:
1. mention the version of tensorflow to be installed in "requirements.txt"
2. Convert the code base to TF2.x

**Comment by naxvm** [comment]
Fixed on #56
