### ISSUE TITLE
NotFoundError: Net/TensorFlow/ssdlite_mobilenet_v2_coco_2018_05_29.pb; No such file or directory

### ISSUE THREAD

**Issue by ayushmankumar7** [JdeRobot/ObjectDetector#50]
"ssd_mobilenet_v2_coco_2018_03_29.pb" present in the model.zip file in Net/Tensorflow but in yml file, it's stated "ssdlite_mobilenet_v2_coco_2018_05_29.pb".

Following Error was seen
![Screenshot from 2020-03-06 13-37-56](https://user-images.githubusercontent.com/41910134/76065083-e8a17680-5fb0-11ea-82dc-546a7a370738.png)

## Possible Fixes

1. Add "ssdlite_mobilenet_v2_coco_2018_05_29.pb" in model.zip 
2. Change yml file to accept "ssd_mobilenet_v2_coco_2018_03_29.pb"

I am solving the problem using the 2nd solution.

**Comment by naxvm** [comment]
Fixed on #56
